project_id = "bnrgbbsleniwykswyjem"

[functions.blaze-proxy]
verify_jwt = false

[functions.ai-predict]
verify_jwt = false

[functions.blaze-auto-bet]
verify_jwt = false

[functions.white-protection-ai]
verify_jwt = false

[functions.update-learned-patterns]
verify_jwt = false

[functions.pattern-research]
verify_jwt = false